version: '3'

services:
  base-service:
    environment:
        SPRING_PROFILES_ACTIVE: docker
        DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
        DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
        DATASOURCE_URL: ${DATASOURCE_URL}
    image: shortlink-service
    ports:
    - 8080:8080
    build:
      context: link-base-service/
    container_name: shortlink-service
    depends_on:
      - postgresDB

  auth-service:
    image: auth-service
    build:
      context: link-authentication-service/
    depends_on:
      - postgresDB

  postgresDB:
    image: postgres:14
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres