version: '3'

services:
  shortlink-service:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    image: shortlink-service
    ports:
    - 8080:8081
    build:
      context: .
    container_name: shortlink-service
    depends_on:
      - postgresDB
  postgresDB:
    image: postgres:14
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres