server:
  port: 8081
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db.changelog-master.xml
    enabled: true

jwt:
  sessionTime: 300_000
  secret: secret_key